<?php
// $Id: simple_themer.module,v 0.1 2008/06/27 16:39:43 tom_o_t Exp $

/*
 * hook_form_alter()
 * alters forms so that after they submit, they theme the page 'simple' in the infowindow
 */

 function simple_themer_form_alter($form_id, &$form){
	// print $form_id . ' '; // this prints form_id's of all forms on every page - development feature

	// first check if we're in the simple theme, and if so, then redirect the results of some forms
	if ($_GET['isSimple']){
		
		switch ($form_id) {
			case 'comment_form':
			$form['#redirect'] = array('node/' . $form['nid']['#value'] . '/simple', 'destination=node&theme=simple', 'tabs-tabs-2');
			unset($form['preview']);
			// print_r($form);
			break;
		}		
	}

 }
 
 
/*
 * hook_init()
 * finds out if we're currently using the simple theme (used inside iframes in greybox and map infowindow)
 * 
 */
 
 function simple_themer_init(){
 	/**
 	 * updated:07/07/2008, Miikka Lammela
 	 * description: At opening ogm function arg is not yet loaded (for some reason).
 	 */
 	if (function_exists('arg')) {
 		if (($_GET['theme']=='simple') || 
		    (arg(0)=='node' && arg(2) == 'simple') || 
			(arg(0)=='forward' && arg(2) == 'simple') || 
			(arg(0)=='abuse' && arg(4) == 'simple') || 
			(arg(0) == 'greenmap_widget') 
		) {
			$_GET['isSimple'] = true;
	 	} else {
			$_GET['isSimple'] = false;
	 	}
	}else {
		if (($_GET['theme']=='simple')){
			$_GET['isSimple'] = true;
		}else {
			$_GET['isSimple'] = false;	
		}	
	}
	
	
 }
 
 function my_very_own_submit($form_id, $form_values) {
 	
	echo 'hello world';
	$_GET['isSimple'] = true;
 }
 
 