<?php 
/*
   list of options for the green map field field_greenhouse_map_nid ("Map Profile at GreenMap.org")
*/

function greenhouseimport_green_map_options() {
  global $user;

  $uid = 0;
  if (arg(0) == 'node' && arg(2) == 'edit' && is_numeric(arg(1))) {
    $node = node_load(arg(1));
    $uid = $node->uid;
  }
  elseif (arg(0) == 'node' && arg(1) == 'add') {
    $uid = $user->uid;
  }
  else {
    return array();
  }

  $options = array();
  $gm_maps = sync_fetch_gm_maps($uid);
  foreach($gm_maps as $gm_map) {
    $options[$gm_map->gm_nid] = $gm_map->title;
  }

  return $options;
}
