<?php

function compact_login_form_alter($form_id, &$form) {
  // print $form_id;
  if ($form_id == 'user_login_block') {
    // print_r($form);
	// die();
	$form[links]['#value'] = '<div class="item-list login-links"><ul><li><a href="' . url('user/register') . '" title="' . t('Create a new user account') . '">' . t('New account') . '</a></li><li><a href="' . url('user/password') . '" title="' . t('Request new password via e-mail') . '">' . t('New password') . '</a></li></ul></div>';
	$module_path = drupal_get_path('module', 'compact_login');
    $settings = array('compactlogin' => array(
      'username' => t('Username / Email'),
      'password' => $form['pass']['#title']
    ));
    drupal_add_js($settings, 'setting');
    drupal_add_js($module_path .'/compact_login.js', 'module');
  }
}