<?php


/**
 * hook_cron()
 * Only run during cron - it's not very important
 * Count the total number of sites in the database
 * Used in the bubble
 */

function gmap_bubble_cron(){

	// get count from database
	$count = db_result(db_query("SELECT COUNT(nid) AS count FROM {node} WHERE type = 'green_site' AND status = '1'"));

	// save count in database
	variable_set('gmap_bubble_site_count', $count);

}

/**
 * hook_menu()
 * create a callback url to get the count - easiest way to access it in JS I think
 */

function gmap_bubble_menu($may_cache){
	$items = array();
	if ($may_cache) {

		$items[] = array(
	      'path' => 'greensite/count',
	      'title' => t('Node Count'),
	      'callback' => 'gmap_bubble_count',
	      'type' => MENU_CALLBACK,
	      'access' => TRUE,
	    );
	}
	return $items;
}

/**
 *	display an informative bubble when loading the gmap.
 *
 *	This function hooks into the gmap module.
 */
function gmap_bubble_gmap($op, $map=null)
{
  if(arg(0) == 'greenmap') {
    $global_map = TRUE;
  }
  elseif (arg(0) == 'node' && is_numeric(arg(1)) && !arg(2)) {
    $type = db_result(db_query('SELECT type FROM node WHERE nid = %d', arg(1)));
    switch ($type) {
      case 'green_map':
        $global_map = TRUE;
        break;
    }
  }

  // do this only for the global map
  if ($global_map) {
    switch ($op) {
      case 'pre_theme_map':
          drupal_add_js(drupal_get_path('module', 'gmap_bubble').'/gmap_bubble.js', 'module', 'footer');
          drupal_add_css(drupal_get_path('module', 'gmap_bubble').'/gmap_bubble.css');
        break;
    }
  }
}
/*
 * Get count of icons - called by hook_menu above
 */

function gmap_bubble_count(){
	echo variable_get('gmap_bubble_site_count', t('many'));
	die();
}
