<?php
// $Id$

/**
 * Alters various forms on the Open Green Map
 *
 * By tom_o_t
 */
function ogm_form_tweaks_form_alter(&$form, &$form_state, $form_id) {
  // print $form_id . ' '; // this prints form_id's of all forms on every page - development feature

  // this one is useful for debugging - replace form_id_here with name of form
  /*
  if($form_id == 'form_id_here') {
    dsm($form);
    $form['form_info'] = array(
      '#value' => '<pre>'. print_r($form, TRUE) .'</pre>'
    );
  }
  */

  switch ($form_id) {
    case 'green_map_node_form':
      $form['field_icons_subset']['#description'] = t('Choose which Green Map Icons can be used on this map. These are the only icons that will appear on your map and its legend. You can always edit your map and change these. If you select none, then all icons will be available.');
      $form['language']['#description'] = t('You can choose the language for this map. If your language is not on this list, leave this blank.');
      $form['locations']['0']['#description'] = t('Click the map to set the location. If you click the wrong location on the map, just click the pin again to relocate it, or drag the pin to the correct location. This will set the latitude-longitude more accurately than entering the address.');

      // tweak the help text on the language selection fields for sites & maps
      $form['language']['#title'] = t('Language Settings');
      $form['language']['#description'] = t('You can choose the language for this site. If your language is not on this list, leave this blank.');
      $form['language']['#options'][''] = t('- None -');
      // Add some guidance about clicking on maps for both sites & maps
      $form['locations']['0']['#description'] = t('Click the map to set the location. If you click the wrong location on the map, just click the pin again to relocate it, or drag the pin to the correct location. This will set the latitude-longitude more accurately than entering the address.');

      //dsm($form);
      /*
      if (isset($form['field_icons_subset'])) {
        ogm_form_tweaks_insertIconRecursive($form['field_icons_subset']);
      }
      */

      // TODO -- re-enable this field when lines & areas are actually available
//       unset($form['field_use_poly']);
      break;

    case 'green_site_node_form':
    // dsm($form_state);
      // tweak the help text on the language selection fields for sites & maps
      $form['language']['#title'] = t('Language Settings');
      $form['language']['#description'] = t('You can choose the language for this site. If your language is not on this list, leave this blank.');
      $form['language']['#options'][''] = t('- None -');
      // Add some guidance about clicking on maps for both sites & maps
      $form['locations']['0']['#description'] = t('Click the map to set the location. If you click the wrong location on the map, just click the pin again to relocate it, or drag the pin to the correct location. This will set the latitude-longitude more accurately than entering the address.');
      $form['locations'][0]['locpick']['user_latitude']['#value'] = $_SESSION['ogmmobilelocation']['lat'];
      // temporarily store the mobile location and add a custom submit handler in ogm_mobile.module to do something with this
     
     $form['#after_build'][] = 'mobile_form_fill_in';
     	 // dsm($form);
      
      $form['#submit'][] = 'ogm_mobile_locationtweak';
      break;

    case 'user_profile_form':
      $form['account']['roles']['#description'] = t('To learn more about the different roles, please click <a href="/faq/how-open-green-map-works/what-are-different-roles-inside-green-mapmaking-team">here</a>.');
      break;
  }
}

/**
* Modify CCK form elements on the example node form.
*/
function mobile_form_fill_in($form, &$form_state) {
  // TODO: Stuff!
	$form['locations'][0]['locpick']['user_latitude']['#value'] = $_SESSION['ogmmobilelocation']['lat'];
	$form['locations'][0]['locpick']['user_longitude']['#value'] = $_SESSION['ogmmobilelocation']['lon'];
  return $form;
}

/**
 *
 * this function modified output of the taxonomy super select ultra
 * (cck_taxonomy_ssu) module, which presents a cck taxonomy multiselect
 * input as a series of checkboxes, by replacing the term name with the
 * appropriate taxonomy image.  cck_taxonomy_ssu was never ported
 * to drupal 6 so this is no longer relevant, but i'm leaving the code
 * here as a model in case it's ever decided to work on this again.
 * --mvc 17nov2009
 *
 */
function ogm_form_tweaks_insertIconRecursive(&$array) {
  foreach ($array as $key => &$item) {
    if (is_array($item)) {
      if (isset($item['#type']) && $item['#type'] == 'checkbox') {
        $item['#title'] = taxonomy_image_display($item['#return_value'], NULL, NULL, array('resize' => '3', 'width' => '21', 'height' => '18', 'imagecache_preset' => 'ORIGINAL')) ."   ". $item['#title'];
      }
      else {
        ogm_form_tweaks_insertIconRecursive($item);
      }
    }
  }
}

function ogm_form_tweaks_form_contact_mail_page_alter(&$form, $form_state) {
  foreach ($form['cid']['#options'] as $cid => $description) {
    $form['cid']['#options'][$cid] = t($description);
  }
}
