<?php

/**
 * Implementation of hook_form_alter().
*/

function ogm_ol_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'green_route_node_form') {

    // need to get lat, lon & center for map
    $node = $form['#node'];
    if ( is_array($node->og_groups) ) {
      // "current()" returns the first element
      $nodegid = current($node->og_groups);
    }
    $gid = $_GET['gids'][0] ? $_GET['gids'][0] : $nodegid;
    $groupnode = node_load($gid);
    $groupmap_settings = array(
      'lat' => $groupnode->location['latitude'],
      'lon' => $groupnode->location['longitude'],
      'zoom' => $groupnode->field_map_zoom[0]['value'],
      'maptype' => $groupnode->field_gmap_type[0]['value'],
    );
    // set a variable to be used by the map_alter hook.
    variable_set('ogm_ol_groupmap_settings', $groupmap_settings);
  }
}

/**
 * Implementation of hook_openlayers_map_alter().
 */
function ogm_ol_openlayers_map_alter(&$map = array()) {
  // pull in the group map data.
  $groupmap = variable_get('ogm_ol_groupmap_settings', NULL);

  // determine the proper gmap type string.
  $default_layer = ogm_ol_gmap_maptype($groupmap['maptype']);

  // since the Drupal OL implementatin currently has trouble with
  // zooms higher tha 15, zoom out to 15 if higher than that.
  if ($groupmap['zoom'] > 15) {
    $zoom = 15;
  }
  else {
    $zoom = $groupmap['zoom'];
  }
  // set values for the map about to be displayed.
  $map['center']['lat'] = $groupmap['lat'];
  $map['center']['lon'] = $groupmap['lon'];
  $map['center']['zoom'] = $zoom;
  $map['default_layer'] = $default_layer;

  // remove the variable to keep it from being used on another map.
  variable_del('ogm_ol_groupmap_settings');
}

/**
 * Helper function to change OGM map type to OL default layer
 */
function ogm_ol_gmap_maptype($groupmaptype) {
  // currently the CCK field that defines this only supports Sattelite and Street
  // this function will need to be updated if that ever changes --ncm
  switch ($groupmaptype) {
    case 'Map':
      $layer = 'openlayers_layers_google_street';
      break;
    case 'Satellite':
      $layer = 'openlayers_layers_google_satellite';
      break;
  }
  return $layer;
}

/**
 * Implementation of hook_init().
 */
function ogm_ol_init() {
  $path = drupal_get_path('module', 'ogm_ol');
  drupal_add_js($path .'/ogm_ol.js', 'module', 'footer');
}

/**
 * Implementation of hook_nodeapi().
 */
function ogm_ol_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  switch ($op) {
    case 'view':
      if ($node->type == 'green_map') {
        $query = 'SELECT ct.nid, AsText(ct.field_line_contour_geo) AS geo
          FROM {content_type_green_route} ct
          LEFT JOIN {node} n ON n.nid = ct.nid AND n.vid = ct.vid
          LEFT JOIN {og_ancestry} oga ON ct.nid = oga.nid
          WHERE n.status = %d
          AND n.type = "%s"
          AND oga.group_nid = %d';
        $result = db_query($query, 1, 'green_route', $node->nid);
        $i = 0;
        $lines = array();
        while ($routes = db_fetch_array($result)) {
          $points = str_replace('LINESTRING(', '', $routes['geo']);
          $points = str_replace(')','', $points);
          $points_arr = explode(',', $points);
          foreach ($points_arr as $key => $value) {
            $coords = explode(' ', $value);
            $lines[$i][] = $coords;
          }
          $i++;
        }
        $js_settings = array('ogm_ol_lines' => array($lines));
        drupal_add_js($js_settings, 'setting');

      }
    break;
  }
}