<?php


// code taken from logintoboggan (which did break the layout for some reason)


/**
 *	add a validation function to the user_login form.
 */
function emaillogin_form_alter($form_id, &$form)
{
	switch ($form_id) {
		case 'user_login':
		case 'user_login_block':
			$form['name']['#title'] = t('Username or Email');
			// $form['name']['#description'] = t('Enter your username or email address');
			$form['#validate'] = array('emaillogin_user_login_validate' => array()) + $form['#validate'];
	  	break;
	}
}


/**
 *	custom validation for user login form.
 *
 *	Changes the name field.
 */
function emaillogin_user_login_validate($form_id, $form_values, $form)
{
	if (isset($form_values['name'])) {
		if ($name = db_result(db_query("SELECT name FROM {users} WHERE LOWER(mail) = LOWER('%s')", $form_values['name'])))
			form_set_value($form['name'], $name);
	}
}