<?php

function ogm_user_upload_file_download($filepath) {
  global $user;
  // prevent anonymous users from viewing imagefield thumbnails, to discourage abuse
  if ( preg_match('#^imagefield_thumbs/user_upload/#', $filepath) ) {
    if ( ! $user->uid ) {
      return -1;
    }
  }
}

function ogm_user_upload_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  if ( $node->type === 'photo' ) {
    if ( $op === 'validate' ) {
      if ( !$a3['#post']['field_photo'][0]['embed'] && !$node->field_image_local[0]['filename'] ) {
        form_set_error('field_photo',
          t('Please choose one of either a user-uploaded photo or a photo from an outside service.'));
      }
    }
  }
}
