<?php

function homepage_views_default_views(){
  $view = new stdClass();
  $view->name = 'greenmap';
  $view->description = 'The Green Map';
  $view->access = array (
);
  $view->view_args_php = '';
  $view->page = TRUE;
  $view->page_title = 'Preview the Open Green Map';
  $view->page_header = '';
  $view->page_header_format = '1';
  $view->page_footer = '';
  $view->page_footer_format = '1';
  $view->page_empty = 'No sites found';
  $view->page_empty_format = '1';
  $view->page_type = 'gmap';
  $view->url = 'greenmap';
  $view->use_pager = FALSE;
  $view->nodes_per_page = '1';
  $view->sort = array (
  );
  $view->argument = array (
  );
  $view->field = array (
    array (
      'tablename' => 'node',
      'field' => 'nid',
      'label' => '',
    ),
    array (
      'tablename' => 'term_node_1',
      'field' => 'name',
      'label' => 'Icon',
      'options' => 'nolink',
    ),
    array (
      'tablename' => 'node',
      'field' => 'title',
      'label' => '',
      'handler' => 'views_handler_field_nodelink',
      'options' => 'link',
    ),
    array (
      'tablename' => 'location',
      'field' => 'latitude',
      'label' => '',
    ),
    array (
      'tablename' => 'location',
      'field' => 'longitude',
      'label' => '',
    ),
    array (
      'tablename' => 'node_data_field_image',
      'field' => 'field_image_embed',
      'label' => '',
      'handler' => 'content_views_field_handler_ungroup',
      'options' => 'image_thumbnail',
    ),
    array (
      'tablename' => 'votingapi_cache_vote_percent_average',
      'field' => 'value',
      'label' => '',
      'handler' => 'fivestar_views_value_display_handler',
    ),
    array (
      'tablename' => 'node_comment_statistics',
      'field' => 'comment_count',
      'label' => '',
      'handler' => 'views_handler_field_int',
    ),
    array (
      'tablename' => 'abuse',
      'field' => 'pending',
      'label' => '',
      'handler' => 'all_flags_views_field_pending_default',
    ),
  );
  $view->filter = array (
    array (
      'tablename' => 'node',
      'field' => 'status',
      'operator' => '=',
      'options' => '',
      'value' => '1',
    ),
    array (
      'tablename' => 'node',
      'field' => 'type',
      'operator' => 'OR',
      'options' => '',
      'value' => array (
  0 => 'green_site',
),
    ),
  );
  $view->exposed_filter = array (
  );
  $view->requires = array(node, term_node_1, location, node_data_field_image, votingapi_cache_vote_percent_average, node_comment_statistics, abuse);
  $views[$view->name] = $view;

  return $views;
}
