<?php
// $Id: simple_themer.module,v 0.1 2008/06/27 16:39:43 tom_o_t Exp $
/*
 * @file
 *  See if a request is calling the "simple theme" by examining the
 *  Drupal path. If so, redirect the results of some forms.
 */

function simple_themer_form_alter(&$form, &$form_state, $form_id) {
  // print $form_id . ' '; // this prints form_id's of all forms on every page - development feature
  if ($_GET['isSimple']) {
    switch ($form_id) {
      case 'comment_form':
        $form['#redirect'] = array('node/'. $form['nid']['#value'] .'/simple', 'destination=node&theme=simple', 'tabs-tabs-2');
        unset($form['preview']);
        break;
    }
  }
}

function simple_themer_init() {
  if (function_exists('arg')) {
    switch (arg(0)) {
      case 'node':
      case 'forward':
        if (arg(2) == 'simple') {
          $_GET['isSimple'] = TRUE;
        }
        break;
      case 'abuse':
        if (arg(4) == 'simple') {
          $_GET['isSimple'] = TRUE;
        }
        break;
      case 'greenmap_widget':
        $_GET['isSimple'] = TRUE;
        break;
      default:
        $_GET['isSimple'] = FALSE;
    }
  }
  else {
    if (($_GET['theme']=='simple')) {
      $_GET['isSimple'] = TRUE;
    }
    else {
      $_GET['isSimple'] = FALSE;
    }
  }
}
