<?php



/**
 * hook_menu()
 * create a callback url to get the count - easiest way to access it in JS I think
 */

function iphone_menu($may_cache){
	$items = array();
	if ($may_cache) {
  
		$items[] = array(
	      'path' => 'iphone/whats_nearby_list', 
	      'title' => t('Iphone What\'s nearby'),
	      'callback' => 'iphone_nearby',
	      'type' => MENU_CALLBACK,
	      'access' => TRUE,
	    );
	    $items[] = array(
	      'path' => 'iphone/search', 
	      'title' => t('Iphone Search'),
	      'callback' => 'iphone_search',
	      'type' => MENU_CALLBACK,
	      'access' => TRUE,
	    );
	    $items[] = array(
	      'path' => 'iphone/resent', 
	      'title' => t('Iphone Resent'),
	      'callback' => 'iphone_resent',
	      'type' => MENU_CALLBACK,
	      'access' => TRUE,
	    );
	}
	return $items;
}

/**
 *	display an informative bubble when loading the gmap.
 *
 *	This function hooks into the gmap module.
 */
 /*
function iphone_gmap($op, $map=null)
{
	switch ($op) {
		case 'pre_theme_map':
			if($_GET['device'] == 'iphone'){
				return;
			}
			// do this only for the global map
			if((arg(0) == 'node' && is_numeric(arg(1))) || (arg(0) == 'greenmap')) {
				drupal_add_js(drupal_get_path('module', 'iphone').'/iphone.js', 'module', 'footer');
				drupal_add_css(drupal_get_path('module', 'iphone').'/iphone.css');
			}
			break;
	}
}
*/

function iphone_gmap($op, $map=null) {
	$path = drupal_get_path('module', 'iphone');
	drupal_add_css($path.'/iphone.css');
}

function detectiPhone(){
	return true;
	$container = $_SERVER['HTTP_USER_AGENT'];
	$useragents = array ("iPhone","iPod");
	foreach ( $useragents as $useragent ) {
		if (eregi($useragent,$container)){
			return true;
		}
	}
	return false;
}
function iphone_search() {
	$_SESSION['parentPage'] = substr($_SERVER['REQUEST_URI'],strlen(base_path()));
	drupal_add_js(drupal_get_path("module", "iphone")."/iphone.js");
	
	
	
	$lat = arg(2);
	$lon = arg(3);
	$search = arg(4);
	
//	$lat = 59.298062;
//	$lon = 18.085127;
	
	$locSQL = '';
	if($lat && $lon) {
		$locSQL = " AND (l.latitude > ".($lat - 0.35)." AND  l.latitude < ".($lat + 0.35)." AND l.longitude > ".($lon - 0.75)." AND l.longitude < ".($lon + 0.75).")";
	}
	
	$r = '';
	$r .= "<div>";
	$r .= "<img id='logo-image' alt=Home' src='".base_path()."sites/all/themes/custom/zen/opengreenmap/logo.png'/>";
	$r .= "<span id='list_header' >".t('Search')."</span>";
	if(!$search){
		$r .= t("Search sites");
	}else {
		// search code
		
	$q = "SELECT DISTINCT(n.nid)
		 FROM {node} AS n " .
		 "INNER JOIN {location}   AS l  ON  n.nid = l.eid
		 INNER JOIN {content_type_green_site} AS ctgs ON n.nid = ctgs.nid
		 INNER JOIN {og_ancestry}   AS oa  ON  n.nid = oa.nid
		 INNER JOIN {node}   AS n2  ON  oa.group_nid = n2.nid
		 INNER JOIN {og}   AS og  ON  n2.nid = og.nid
		 
		 WHERE n.type ='green_site' AND n.status = '1' AND oa.is_public = '1' AND n2.status = '1' AND og.private = '0' ".
		// "AND ctgs.field_details_value LIKE '%".$search."%' OR n.title LIKE '%".$search."%'".
		 $locSQL.	
		" ORDER BY n.nid";
		$result = db_query($q);
	//echo $q;
		$r .= "<ul>";
		// we're showing only ten results 
		while ($row = db_fetch_object($result)) {
			$currentNode = node_load(array('nid'=>$row->nid));
				if(count(explode($search,$currentNode->title)) <= 1 
				&& count(explode($search,$currentNode->field_details[0]['value'])) <= 1) {continue;}			
			// "AND ctgs.field_details_value LIKE '%".$search."%' OR n.title LIKE '%".$search."%'".
			
				$r .= "<li><span id='".$currentNode->nid."' class='genre'>".$currentNode->title."</span></li>";
				$r .= "<div id='".$currentNode->nid."-list' class='genre_content'>";
				if(strlen($currentNode->field_details[0]['value']) > 0){
					$r .= l(substr($currentNode->field_details[0]['value'],0,60) ."...",$currentNode->path);	
				}else {
					$r .= l(t('Read more'),$currentNode->path);
				}
				
				

				$r.= "</div>";

			
			//print_r($currentNode);
			//break;
		}
		$r .= "</ul>";
		

	}
		
	
	$r.= "</div>";
	return $r;
	
}
function iphone_resent() {//created
	$_SESSION['parentPage'] = substr($_SERVER['REQUEST_URI'],strlen(base_path()));
	drupal_add_js(drupal_get_path("module", "iphone")."/iphone.js");
	
	
	$lat = arg(2);
	$lon = arg(3);
	
	//echo $lat ." " . $lon;
	
//	$lat = 59.298062;
//	$lon = 18.085127;
	
	$add_zoomSQL = "AND (l.latitude > ".($lat - 0.35)." AND  l.latitude < ".($lat + 0.35)." AND l.longitude > ".($lon - 0.75)." AND l.longitude < ".($lon + 0.75).")";
	
	
	$r = '';
	$r .= "<div>";
	$r .= "<img id='logo-image' alt=Home' src='".base_path()."sites/all/themes/custom/zen/opengreenmap/logo.png'/>";
	$r .= "<span id='list_header' >".t('Resent')."</span>";
	
	$locSQL = '';
	if($lat && $lon) {
		$locSQL = " AND (l.latitude > ".($lat - 0.35)." AND  l.latitude < ".($lat + 0.35)." AND l.longitude > ".($lon - 0.75)." AND l.longitude < ".($lon + 0.75).")";
	}
		// search code
		
	$q = "SELECT DISTINCT(n.nid)
		 FROM {node} AS n" .
		 "
		 INNER JOIN {location}   AS l  ON  n.nid = l.eid
		 INNER JOIN {content_type_green_site} AS ctgs ON n.nid = ctgs.nid
		 INNER JOIN {og_ancestry}   AS oa  ON  n.nid = oa.nid
		 INNER JOIN {node}   AS n2  ON  oa.group_nid = n2.nid
		 INNER JOIN {og}   AS og  ON  n2.nid = og.nid
		 
		 WHERE n.type ='green_site' AND n.status = '1' AND oa.is_public = '1' AND n2.status = '1' AND og.private = '0' ".
		 $locSQL.	
		" ORDER BY n.nid DESC limit 10";
		$result = db_query($q);
	//	return $q;
		$r .= "<ul>";
		
		// we're showing only ten results 
		while ($row = db_fetch_object($result)) {
			$currentNode = node_load(array('nid'=>$row->nid));
				$r .= "<li><span id='".$currentNode->nid."' class='genre'>".$currentNode->title."</span></li>";
				$r .= "<div id='".$currentNode->nid."-list' class='genre_content'>";
				if(strlen($currentNode->field_details[0]['value']) > 0){
					$r .= l(substr($currentNode->field_details[0]['value'],0,60) ."...",$currentNode->path);	
				}else {
					$r .= l(t('Read more'),$currentNode->path);
				}
				
				

				$r.= "</div>";

			/*
			print_r($currentNode);
			break;*/
		}
		$r .= "</ul>";
	
	$r.= "</div>";
	return $r;
}
function iphone_nearby(){
	
	//echo $_SERVER['REQUEST_URI'] ."<br>";
	//echo base_path();
	$_SESSION['parentPage'] = substr($_SERVER['REQUEST_URI'],strlen(base_path()));
//	drupal_add_css(drupal_get_path('module', 'iphone').'/iphone.css');
//	echo base_path() . "misc/jquery.js";
	drupal_add_js(drupal_get_path("module", "iphone")."/iphone.js");
	
	///dev/ogm_miikka2/misc/jquery.js
	
	
	$lat = arg(2);
	$lon = arg(3);
	$filter = arg(4);
	//echo $lat ." " . $lon;
	
	$lat = 59.298062;
	$lon = 18.085127;
	
	 $add_zoomSQL = "AND (l.latitude > ".($lat - 0.35)." AND  l.latitude < ".($lat + 0.35)." AND l.longitude > ".($lon - 0.75)." AND l.longitude < ".($lon + 0.75).")";
	
	
	$q = "SELECT DISTINCT(n.nid)
		 FROM {node} AS n
		 INNER JOIN {location}   AS l  ON  n.nid = l.eid
		 INNER JOIN {og_ancestry}   AS oa  ON  n.nid = oa.nid
		 INNER JOIN {node}   AS n2  ON  oa.group_nid = n2.nid
		 INNER JOIN {og}   AS og  ON  n2.nid = og.nid" .
		 "
		 WHERE l.type = 'node'  AND n.type ='green_site' AND n.status = '1' AND oa.is_public = '1' AND n2.status = '1' AND og.private = '0' ".
		 $add_zoomSQL.
		"ORDER BY n.nid";
		
	/*
		$result = db_query($q);
		
		$r .= "<ul>";
		
		// we're showing only ten results 
		while ($row = db_fetch_object($result)) {
			$currentNode = node_load(array('nid'=>$row->nid));
				// case lause
				$r .= "<li><span id='".$currentNode->nid."' class='genre'>".$currentNode->title."</span></li>";
				$r .= "<div id='".$currentNode->nid."-list' class='genre_content'>";
				if(strlen($currentNode->field_details[0]['value']) > 0){
					$r .= l(substr($currentNode->field_details[0]['value'],0,60) ."...",$currentNode->path);	
				}else {
					$r .= l(t('Read more'),$currentNode->path);
				}
				
				

				$r.= "</div>";

//print_r($currentNode);
			
		//	print_r($currentNode);
			break;
		}
		$r .= "</ul>";
	*/
//	return $r;
	//food
	$view = null;
	$view = views_get_view('whats_nearby_list_block');
	$view->args[0]='Food';
	$food = views_build_view('block', $view,$view->args, false, false);
	
	//shopping
	$view = null;
	$view = views_get_view('whats_nearby_list_block');
	$view->args[0]='Shopping';
	$shopping = views_build_view('block', $view,$view->args, false, false);
	
	//getting Around
	$view = null;
	$view = views_get_view('whats_nearby_list_block');
	$view->args[0]='getting_around';
	$getting_around = views_build_view('block', $view,$view->args, false, false);
	
	//energy
	$view = null;
	$view = views_get_view('whats_nearby_list_block');
	$view->args[0]='energy';
	$energy = views_build_view('block', $view,$view->args, false, false);
	
	//nature
	$view = null;
	$view = views_get_view('whats_nearby_list_block');
	$view->args[0]="nature";
	$nature = views_build_view('block', $view,$view->args, false, false);
	
	//Green Culture
	$view = null;
	$view = views_get_view('whats_nearby_list_block');
	$view->args[0]="green culture";
	$green_culture = views_build_view('block', $view,$view->args, false, false);
	
	//more categories (another view)
	$view = null;
	$view = views_get_view('');
	$view->args[0]=$user->uid;
	$more_categories = views_build_view('block', $view,$view->args, false, false);
	
	$r = '';
/*	$r .= "<style type='text/css' media='all'>@import '".drupal_get_path("module", "iphone")."/iphone.css';</style>";
	$r .= "<script type='text/javascript' src='".base_path() . "misc/jquery.js'></script>";
	$r .= "<script type='text/javascript' src='".drupal_get_path("module", "iphone")."/iphone.js'></script>";*/
	
	
	$r .= "<div>";
	$r .= "<img id='logo-image' alt=Home' src='".base_path()."sites/all/themes/custom/zen/opengreenmap/logo.png'/>";
	$r .= "<span id='list_header' >".t('Nearby Sites')."</span>";
	$r .= "<ul>";
	$r .= "<li><span id='food' class='genre'>Food</span></li>";
	$r .= "<div id='food-list' class='genre_content'>";
	$r .= $food;
	$r.= "</div>";
	
	$r .= "<li><span id='shopping' class='genre'>Shopping</span></li>";
	$r.= "<div id='shopping-list' class='genre_content'>";
	$r .= $shopping;
	$r.= "</div>";
	/*$r .= "<li>Getting Around</li>";
	$r .= $getting_around;*/
	
	$r .= "<li><span id='energy' class='genre'>Energy</span></li>";
	$r.= "<div id='energy-list' class='genre_content'>";
	$r .= $energy;
	$r.= "</div>";
	$r .= "<li><span id='nature' class='genre'>Nature</span></li>";
	$r.= "<div id='nature-list' class='genre_content'>";
	$r .= $nature;
	$r.= "</div>";
	$r .= "</ul>";
	
/*	$r .= "<li>Green Culture</li>";
	$r .= $green_culture;*/
	
	/*
	$r .= "<li><span>More Categories</span></li>";
	$r .= "</ul>";
	*/
	/*
	$r .= "<span>Top sites nearby</span>";
	*/
	// block view
	$r .= "";
	$r .= "";
	$r .= "";
	$r .= "";
	
	$r .= "";
	
	$r.= "</div>";
	return $r;
	//echo $r;
	
}
