<?php
// $Id: messagefx.module,v 1.1.2.1 2007/04/26 21:14:28 jjeff Exp $

/**
 * Implementation of hook_menu()
 */
function messagefx_menu($may_cache) {
  $items = array();
  if ($may_cache) {
    // settings
    $items[] = array(
      'path' => 'admin/settings/messagefx',
      'title' => t('Messaging Settings'),
      'description' => t('Change the effects applied to Drupal messages.'),
      'callback' => 'drupal_get_form',
      'callback arguments' => array('messagefx_settings'),
      'access' => user_access('administer site configuration'),
     );
  }
  return $items;
}

/**
 * Implementation of hook_footer()
 */
function messagefx_footer() {
  if (drupal_get_messages(NULL, FALSE)) {
    jquery_interface_add();
    
    switch (variable_get('status_effect', 'Pulsate')) {
      case 'Pulsate' :
        $js = "\$('.status').Pulsate(". variable_get('status_length', 200) .", ". variable_get('status_times', 6) .");";
        break;
      case 'Shake' :
        $js = "\$('.status').Shake(". variable_get('status_times', 5) .");";
        break;
      case 'Highlight' :
        $js = "\$('.status').Highlight(". variable_get('status_length', 500) .", '". variable_get('status_highlight_color', '#FF3') ."');";
        break;
    }
    switch (variable_get('error_effect', 'Pulsate')) {
      case 'Pulsate' :
        $js .= "\$('.error').Pulsate(". variable_get('error_length', 200) .", ". variable_get('error_times', 6) .");";
        break;
      case 'Shake' :
        $js .= "\$('.error').Shake(". variable_get('error_times', 5) .");";
        break;
      case 'Highlight' :
        $js .= "\$('.error').Highlight(". variable_get('error_length', 500) .", '". variable_get('error_highlight_color', '#F00') ."');";
        break;
    }
    if ($js) {
      $js = '$(window).load(function(){'. $js .'});';
      drupal_add_js($js, 'inline', 'header');
    }
  }
}

/**
 * Settings form
 */
function messagefx_settings() {
  $form['fx'] = array('#type' => 'fieldset', '#title' => t('Effects'));
  $fx_options = variable_get('spajax_fx_options', array('' => 'none', 'Pulsate' => 'Pulsate', 'Shake' => 'Shake', 'Highlight' => 'Highlight'));
  $form['fx']['status_effect'] = array(
    '#type' => 'select',
    '#title' => t('Status Message Effect'), 
    '#default_value' => variable_get('status_effect', 'Pulsate'), 
    '#options' => $fx_options,
    '#description' => t('Effect added to Drupal status messages'), 
  );
  $form['fx']['stat_adv'] = array(
    '#type' => 'fieldset',
    '#title' => t('Timing'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );
  $form['fx']['stat_adv']['status_length'] = array(
    '#type' => 'textfield',
    //'#size' => 5,
    '#title' => t('Length of each'), 
    '#default_value' => variable_get('status_length', 500), 
    '#description' => t('In milliseconds -- Length of each iteration of the effect.'), 
  );
  $form['fx']['stat_adv']['status_times'] = array(
    '#type' => 'textfield',
    //'#size' => 5,
    '#title' => t('Number of times'), 
    '#default_value' => variable_get('status_times', 5), 
    '#description' => t('Number of times to apply the effect.'), 
  );
  
  
  $form['fx']['error_effect'] = array( 
    '#type' => 'select', 
    '#title' => t('Error Message Effect'), 
    '#default_value' => variable_get('error_effect', 'Pulsate'), 
    '#options' => $fx_options,
    '#description' => t('Effect added to Drupal error messages'), 
  );
  $form['fx']['error_adv'] = array(
    '#type' => 'fieldset',
    '#title' => t('Timing'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );
  $form['fx']['error_adv']['error_length'] = array(
    '#type' => 'textfield',
    //'#size' => 5,
    '#title' => t('Length of each'), 
    '#default_value' => variable_get('error_length', 500), 
    '#description' => t('In milliseconds -- Length of each iteration of the effect.'), 
  );
  $form['fx']['error_adv']['error_times'] = array(
    '#type' => 'textfield',
    //'#size' => 5,
    '#title' => t('Number of times'), 
    '#default_value' => variable_get('error_times', 5), 
    '#description' => t('Number of times to apply the effect.'), 
  );
  
  return system_settings_form($form);
}

/**
 * Validation function for settings form
 */
function messagefx_settings_validate($form_id, $form_values) {
  foreach(array('status_length', 'status_times', 'error_length', 'error_times') as $field) {
    if (!is_numeric($form_values[$field])) {
      form_set_error($field, t('All values need to be numbers.'));
    }
  }
}
