<?php

/**
 * hook_form_alter
 * To alter various forms on the Open Green Map
 *
 * By tom_o_t
 */

function ogm_form_tweaks_form_alter($form_id, &$form){
	// print $form_id . ' '; // this prints form_id's of all forms on every page - development feature

	// this one is useful for debugging - replace form_id_here with name of form
	/* if($form_id == 'form_id_here') {
		   $form['form_info'] = array(
			 '#value' => '<pre>'. print_r($form, TRUE) .'</pre>'
		   );
	} */
  switch ($form_id) {
    case 'green_site_node_form':
    case 'green_map_node_form':
      // There are several fields that appear on both the Green Site and the Green Map forms. This if statement deals with both.

     // tweak the help text on the language selection fields for sites & maps
    $form['i18n']['language']['#description'] = t('If your language is not on this list, leave this blank.');

    // Add some guidance about clicking on maps for both sites & maps
    $form['locations']['0']['#description'] = t('If you click the wrong location on the map, just click the pin again to remove it, or drag the pin to the correct location. You can also just click the new location and the pin will be moved.');

    if(isset($form['field_icons_to_use'])) {
      ogm_form_tweaks_insertIconRecursive($form['field_icons_to_use']);
    }
    break;
  }
}

function ogm_form_tweaks_insertIconRecursive(&$array) {
  foreach($array as $key => &$item) {
    if(is_array($item)) {
      if(isset($item['#type']) && $item['#type'] == 'checkbox') {
        $item['#title'] = taxonomy_image_display($item['#return_value'], NULL, NULL, array('resize' => '3', 'width' => '21', 'height' => '18', 'imagecache_preset' => 'ORIGINAL')). "   ".$item['#title'];
      }
      else {
        ogm_form_tweaks_insertIconRecursive($item);
      }
    }
  }
}