<?php

/**
 * hook_menu()
 * create a callback url to get the count - easiest way to access it in JS I think
 */

function sms_menu($may_cache){
	$items = array();
	if ($may_cache) {
  
		
	} else {
		$items[] = array(
	      'path' => 'sms', 
	      'title' => t('SMS Query'),
	      'callback' => 'sms_lookup',
		  'callback_arguments' => arg(1),
	      'type' => MENU_CALLBACK,
	      'access' => TRUE,
	    );
	}
	return $items;
}

function sms_lookup($arg=NULL){
	// echo $_GET[address];
	// echo 'hello world';
	
	//Three parts to the querystring: q is address, output is the format, key is the GAPI key
	$key = variable_get('googlemap_api_key','ABQIAAAA1P6vBz0CKnLVelm4sfu7shT2yXp_ZAY8_ufC3CFXhHIE1NvwkxTrGJODvKAg_vTWRxila0Fn6T6FVA');
	//$address = urlencode("columbia MO");
	
	$address = urlencode($_GET[address]);
	// echo $address;
	//If you want an extended data set, change the output to "xml" instead of csv
	$url = "http://maps.google.com/maps/geo?q=".$address."&output=csv&key=".$key;
	//Set up a CURL request, telling it not to spit back headers, and to throw out a user agent.
	$ch = curl_init();
	 
	curl_setopt($ch, CURLOPT_URL, $url);
	curl_setopt($ch, CURLOPT_HEADER,0); //Change this to a 1 to return headers
	curl_setopt($ch, CURLOPT_USERAGENT, $_SERVER["HTTP_USER_AGENT"]);
	curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	 
	$data = curl_exec($ch);
	curl_close($ch);

  
	
	//Check our Response code to ensure success
	if (substr($data,0,3) == "200")
	{
		$data = explode(",",$data);
		 
		$precision = $data[1];
		$latitude = $data[2];
		$longitude = $data[3];
	 
	} else {
		echo "Could not understand your address, sorry! Http error ".substr($data,0,3);
		echo $address;
		echo $latitude . ',' . $longitude;
		die();
	}	
	
	// stick lat & long into our database query
	drupal_goto($path = 'sms_list', $query = 'op0=1&latitude=' . $latitude . '&longitude=' . $longitude);
	
	// die();
}

/*
* default sms view 
*/

function sms_views_default_views() {
// sms list view _ NOT WORKING - perhaps update location.module?
// using this for textmarks

  $view = new stdClass();
  $view->name = 'sms_list';
  $view->description = '';
  $view->access = array (
);
  $view->view_args_php = '';
  $view->page = TRUE;
  $view->page_title = '';
  $view->page_header = '';
  $view->page_header_format = '1';
  $view->page_footer = '';
  $view->page_footer_format = '1';
  $view->page_empty = '';
  $view->page_empty_format = '1';
  $view->page_type = 'table';
  $view->url = 'sms_list';
  $view->use_pager = TRUE;
  $view->nodes_per_page = '3';
  $view->sort = array (
  );
  $view->argument = array (
  );
  $view->field = array (
    array (
      'tablename' => 'node',
      'field' => 'title',
      'label' => '',
      'handler' => 'views_handler_field_nodelink',
      'options' => 'link',
    ),
  );
  $view->filter = array (
    array (
      'tablename' => 'node',
      'field' => 'type',
      'operator' => 'OR',
      'options' => '',
      'value' => array (
  0 => 'green_site',
),
    ),
    array (
      'tablename' => 'node',
      'field' => 'distinct',
      'operator' => '=',
      'options' => '',
      'value' => array (
  0 => 'distinct',
),
    ),
    array (
      'tablename' => 'location',
      'field' => 'proximity_map',
      'operator' => '5',
      'options' => '',
      'value' => 'Array',
    ),
  );
  $view->exposed_filter = array (
    array (
      'tablename' => 'location',
      'field' => 'proximity_map',
      'label' => '',
      'optional' => '1',
      'is_default' => '0',
      'operator' => '1',
      'single' => '0',
    ),
  );
  $view->requires = array(node, location);
  $views[$view->name] = $view;
  return $views;
}
