<?php
/**
 * Implementation of hook_menu
 *   Add menu custom menu items here, instead of through the inerface
 *   This will make it easier to move these things via SVN and never lose them.
 *   They will still need to be enabled and moved.
 */
function ogm_custom_misc_menu($may_cache) {
}

/**
 * Views argument handling for site page mini maps
 */


function ogm_custom_misc_view_args_site_mini_map($args, $view) {
  if (!$args && arg(0) == 'node' && is_numeric(arg(1)) && !arg(2)) {
    $args[0] = arg(1);

    // grab the lat and long of the site to center the map
    $query = db_query('SELECT l.latitude, l.longitude FROM {location} l INNER JOIN {location_instance} li ON l.lid = li.lid INNER JOIN {node} n ON n.nid = li.nid AND n.vid = li.vid WHERE li.nid= %d', $args[0]);
    $geocodes = db_fetch_array($query);


    // build the gmap macro
    $macro = '[gmap zoom=15 |';
    $macro .= 'center='. $geocodes['latitude'] .','. $geocodes['longitude'] .' |';
    $macro .= 'width=175px |height=175px |control=None |type=Map | tcontrol=off | scontrol=off|drag=no|align=center]';

    // add the macro to the view
    $view->gmap_macro = $macro;

    // list the maps that this site is on
    $groups = db_query('SELECT DISTINCT(group_nid) FROM {og_ancestry} WHERE nid = %d', $args[0]);

    $links = '<ul>';
    while ($group = db_fetch_object($groups)) {
      $mapname = db_result(db_query('SELECT title FROM {node} WHERE nid = %d', $group->group_nid));
      $links .= '<li>'. l($mapname, 'node/'. $group->group_nid) .'</li>';
    }
    $links .= '</ul>';
    // add the links to the block footer
    $view->block_header = '<span class="jto">'. t('Jump To:') .' </span>'. $links;
  }
  return $args;
}


/**
 * Front page code
 */
function ogm_custom_misc_front_page() {
  // create different 'get involved' links depending on whether they're loggedin or not
  global $user;
  if($user->uid != 0){
    $involved_link = url('faq/about-website/how-can-i-add-open-green-map');
  } else {
    $involved_link = url('user/register');
  }

  // define the three blocks accross the front page
  $output ='
  <div id="bigbuttons" class="clear-block">
    <ul class="big clear-block">
      <li class="explore big">
        <h2 class="explore"><a class="bigbuttons explore" href="'. url('greenmap') .'">'. t('Explore') .'</a></h2>
        <p><a class="bigbuttons" href="'. url('greenmap') .'">'.  variable_get('gmap_bubble_site_count', t('many')) .' local green living sites! See the world from a new perspective.
</a></p>
      </li>
      <li class="expand big">
        <h2 class="latest"><a class="bigbuttons latest" href="'. url('greenmap/recent') .'">'. t('Fresh Maps') .'</a></h2>';
         // embed the recent maps block here
        $list_of_impacts_view = views_get_view('recent_maps');
        $list = views_build_view('embed', $list_of_impacts_view, NULL, false, 3);
        $output .= $list;

      $output .= '</li>
      <li class="exchange big">
        <h2 class="involved"><a class="bigbuttons involved" href="'. $involved_link .'">'. t('Get Involved!') .'</a></h2>
        <p><a class="bigbuttons" href="'. $involved_link .'">'. t('Add comments,/ ratings, images and impacts to any site or create a new Open Green Map!') .'</a><p>
      </li>
    </ul>';

  // main body text of the front page

  $output .= '<div id="homepagetext" class="clear-block">
    <p><strong>Discover New Directions to a Sustainable Future!</strong></p>

    <p>Open Green Map charts natural, cultural and green living sites in your community and around the world. Use it today to green up your life!</p>

    <p>Now, you are invited to '. l('add', 'faq/883') .' images, ratings and impacts for each green site.'. l('More features are in progress', 'design')  .', leading up to our '. l('June 5 launch celebration', 'about') .'.</p>

    <p>With inclusive participation in sustainable development our mission since 1995, Green Map System welcomes you to the Open Green Map. '. l(t('Support'), 'donate') .' our locally-led '. l(t('global movement'), 'http://GreenMap.org') .' now in more than 50 countries.</p>

    <p><em class="pink">Think Global, Map Local!</em></p>
  </div>
  </div>';

  print $output;
}

function ogm_custom_misc_large_block_menu() {
  $gmap = '<li class="grmap">'. l(t('World Map'), 'greenmap') .'</li>';
  $maps = '<li class="maps">'. l(t('All Maps'), 'maps/recent') .'</li>';
  $userlink = '<li class="involved">'. l(t('Get Involved!'), 'user/register') .'</li>';
  switch (arg(0)) {
    case 'greenmap':
      $gmap = '<li class="grmap-active">'. l(t('World Map'), 'greenmap') .'</li>';
      break;
    case 'maps':
        $maps = '<li class="maps-active">'. l(t('All Maps'), 'maps/recent') .'</li>';

    case 'user':
      if (arg(1) == 'register') {
        $userlink = '<li class="involved-active">'. l(t('Get Involved!'), 'user/register') .'</li>';
      }
      break;
  }

  global $user;
  $output = '<div id="large-block-menu"><ul>';
  $output .= $gmap . $maps;
  if ($user->uid == 0) {
    $output .= $userlink;
  }
  $output .= '</ul></div><!-- /large-block-menu -->';

  print $output;
}