<?php
/**
 * Implementation of hook_menu
 *   Add menu custom menu items here, instead of through the inerface
 *   This will make it easier to move these things via SVN and never lose them.
 *   They will still need to be enabled and moved.
 */
// function ogm_custom_misc_menu() {
// }

/**
 * Build gmap macro for site page mini map, given the coordinates
 */
function ogm_custom_misc_site_mini_map($latitude, $longitude) {
  // build the gmap macro
  $macro = '[gmap zoom=15 |';
  $macro .= "center=$latitude,$longitude |";
  $macro .= 'width=175px |height=175px |control=None |type=Map | tcontrol=off | scontrol=off|drag=no|align=center]';
  return $macro;
}

/**
 * Front page code
 */
function ogm_custom_misc_front_page() {
  // create different 'get involved' links depending on whether they're loggedin or not
  global $user;
  if($user->uid != 0){
    $involved_link = url('faq/about-website/how-can-i-create-open-green-map');
  } else {
    $involved_link = url('user/register');
  }

  // define the three blocks accross the front page
  $output ='
  <div id="bigbuttons" class="clear-block">
    <ul class="big clear-block">
      <li class="explore big">
        <h2 class="explore"><a class="bigbuttons explore" href="'. url('greenmap') .'">'. t('Explore') .'</a></h2>
        <p><a class="bigbuttons" href="'. url('greenmap') .'">'.
        t('@count green living sites!<br />See the world from a<br />new perspective', array('@count' => variable_get('gmap_bubble_site_count', t('many')))).
        '</a></p>
      </li>
      <li class="expand big">
        <h2 class="latest"><a class="bigbuttons latest" href="'. url('maps/recent') .'">'. t('Fresh Maps') .'</a></h2>';

      // TODO: eventually we should move this back to using views, but since
      // there isn't the right sort option from views, and this is a very
      // complext dataset. Perhaps this may be less overhead than views

         // embed the recent maps block here
//         $list = views_embed_view('maps', 'block_1');
//         $output .= $list;

      $query = db_query('SELECT DISTINCT(tmp2.nid), tmp2.title FROM
        (SELECT n.nid AS nid, n.title FROM {node} n JOIN
          (SELECT oga.group_nid, n.changed AS changed FROM {node} n
          INNER JOIN og_ancestry oga ON n.nid=oga.nid
          WHERE n.status = %d AND oga.is_public = %d)
        tmp ON tmp.group_nid = n.nid
        INNER JOIN {og} AS og ON n.nid=og.nid
        WHERE n.type = "%s"
        AND og.og_private = %d
        ORDER BY tmp.changed DESC)
      tmp2 LIMIT %d', 1, 1, 'green_map', 0, 3);

      $i = 0;
      while ($result = db_fetch_object($query)) {
        if ($i > 0) {
          $output .= '<br />';
        }
        $output .= l(t($result->title), 'node/'. $result->nid);
        $i++;
      }
      $output .= '</li>
      <li class="exchange big">
        <h2 class="involved"><a class="bigbuttons involved" href="'. $involved_link .'">'. t('Get Involved!') .'</a></h2>
        <p><a class="bigbuttons" href="'. $involved_link .'">'. t('Explore local sites. Add your thoughts. Suggest a new site. Or create a new map!') .'</a><p>
      </li>
    </ul>';

  // main body text of the front page

  $output .= '<div id="homepagetext" class="clear-block">
    <p><strong>'.
    t('Green Living Sites. Nature. Social and Cultural Resources. Find them all on the Green Map!').
    '</strong></p><p>'.
    t('Interact with thousands of great places charged by local Green Mapmakers around the world. <br />Make these places part of your life, and help your community become a greener and healthier place.').
    '</p><p>'.
    t('Open Green Maps are designed to be explored, customized and enhanced by people like you. <br />You can share your insights, ratings and images or suggest, compare and share sites.').
    ' '.'</p><p>'.
    t('<a href="@greenmap_link">Green Map System</a> promotes inclusive participation in sustainable development, engaging hundreds of communities in 65 countries in mapmaking since 1995. Get involved and <a href="@support">support</a> this global movement!', array('@greenmap_link' => url('http://greenmap.org'), '@support' => url('donate'))).
    '</p><p><em class="pink">'.
    t('Think Global, Map Social!').
    '</em></p> </div> </div>';

  print $output;
}

function ogm_custom_misc_large_block_menu() {
  $gmap = '<li class="grmap">'. l(t('World Map'), 'greenmap') .'</li>';
  $maps = '<li class="maps">'. l(t('All Maps'), 'maps') .'</li>';
  $userlink = '<li class="involved">'. l(t('Get Involved!'), 'user/register') .'</li>';
  switch (arg(0)) {
    case 'greenmap':
      $gmap = '<li class="grmap-active">'. l(t('World Map'), 'greenmap') .'</li>';
      break;
    case 'maps':
        $maps = '<li class="maps-active">'. l(t('All Maps'), 'maps') .'</li>';

    case 'user':
      if (arg(1) == 'register') {
        $userlink = '<li class="involved-active">'. l(t('Get Involved!'), 'user/register') .'</li>';
      }
      break;
  }

  global $user;
  $output = '<div id="large-block-menu"><ul>';
  $output .= $gmap . $maps;
  if ($user->uid == 0) {
    $output .= $userlink;
  }
  $output .= '</ul></div><!-- /large-block-menu -->';

  print $output;
}

function ogm_custom_misc_views_api() {
  return array('api' => 2.0,);
}
